name: clippr
region: nyc
static_sites:
  - name: web
    environment_slug: html
    source_dir: /project
    github:
      repo: keviscoding/clippr
      branch: main
      deploy_on_push: true
    index_document: index.html
    catchall_document: index.html
